#!/usr/bin/env python3
"""
Send the weekly meal plan PDF via Gmail SMTP using an app password.
No OAuth required — works headlessly in GitHub Actions.
Set GMAIL_APP_PASSWORD in .env (or as a GitHub secret).
"""

import json
import os
import smtplib
import sys
from datetime import date
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).parent.parent
COMPASS_ROOT = ROOT.parent.parent
load_dotenv(COMPASS_ROOT / ".env")

DATA_DIR = ROOT / "data"
CONFIG_PATH = ROOT / "config" / "user_preferences.json"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


def build_email_body(plan: dict) -> str:
    week_of = plan.get("week_of", date.today().isoformat())
    cost = plan.get("estimated_weekly_cost_usd", 0)
    targets = plan.get("macro_targets", {})

    return f"""
    <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#1a1a2e;">
      <div style="background:#1a1a2e;padding:24px;border-radius:8px 8px 0 0;">
        <h1 style="color:white;margin:0;font-size:22px;">Your Meal Plan</h1>
        <p style="color:#aaa;margin:6px 0 0;">Week of {week_of}</p>
      </div>
      <div style="padding:24px;border:1px solid #eee;border-top:none;border-radius:0 0 8px 8px;">
        <h2 style="color:#e94560;font-size:16px;margin-top:0;">This Week at a Glance</h2>
        <table style="border-collapse:collapse;width:100%;">
          <tr style="background:#f5f5f5;">
            <td style="padding:10px;font-weight:bold;">Estimated grocery cost</td>
            <td style="padding:10px;">${cost:.2f}</td>
          </tr>
          <tr>
            <td style="padding:10px;font-weight:bold;">Daily protein target</td>
            <td style="padding:10px;">{targets.get('protein_g', 175)}g</td>
          </tr>
          <tr style="background:#f5f5f5;">
            <td style="padding:10px;font-weight:bold;">Daily calorie target</td>
            <td style="padding:10px;">{targets.get('calories', 3100)} kcal</td>
          </tr>
          <tr>
            <td style="padding:10px;font-weight:bold;">Meals per day</td>
            <td style="padding:10px;">5 (breakfast, lunch, dinner + 2 snacks)</td>
          </tr>
        </table>
        <p style="margin-top:20px;color:#555;font-size:14px;">
          Your full meal plan and grocery list are attached as a PDF.
          Print it or open it on your phone while you shop.
        </p>
        <p style="margin-top:12px;color:#555;font-size:14px;">
          Log actual cost and a rating in the Compass dashboard (More → Health)
          so next week's plan learns from it.
        </p>
        <hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
        <p style="font-size:12px;color:#aaa;">
          Generated by Compass · Runs every Sunday at 8am
        </p>
      </div>
    </div>
    """


def send_email(pdf_path: Path, plan: dict, config: dict):
    to = config["profile"]["email"]
    from_addr = config["profile"]["email"]
    week_of = plan.get("week_of", date.today().isoformat())
    subject = f"Your Meal Plan – Week of {week_of}"
    app_password = os.getenv("GMAIL_APP_PASSWORD")

    if not app_password:
        print("GMAIL_APP_PASSWORD not set. PDF saved locally:")
        print(f"  {pdf_path}")
        print("Add GMAIL_APP_PASSWORD to .env or GitHub secrets to enable email delivery.")
        return

    msg = MIMEMultipart("mixed")
    msg["From"] = from_addr
    msg["To"] = to
    msg["Subject"] = subject

    msg.attach(MIMEText(build_email_body(plan), "html"))

    with open(pdf_path, "rb") as f:
        pdf_part = MIMEApplication(f.read(), _subtype="pdf")
    pdf_part.add_header("Content-Disposition", "attachment", filename=pdf_path.name)
    msg.attach(pdf_part)

    print(f"Connecting to Gmail SMTP...")
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(from_addr, app_password)
        server.sendmail(from_addr, to, msg.as_string())

    print(f"Email sent to {to} — Subject: {subject}")


def main():
    config = load_config()
    plan_path = DATA_DIR / "meal_plan.json"

    if not plan_path.exists():
        print("Error: data/meal_plan.json not found. Run generate_meal_plan.py first.")
        sys.exit(1)

    with open(plan_path) as f:
        plan = json.load(f)

    week_of = plan.get("week_of", date.today().isoformat())
    pdf_path = DATA_DIR / f"meal_plan_{week_of}.pdf"

    if not pdf_path.exists():
        print(f"Error: {pdf_path} not found. Run generate_pdf.py first.")
        sys.exit(1)

    send_email(pdf_path, plan, config)


if __name__ == "__main__":
    main()
